name: flutter_shufflr
description: Flutter version of the Shufflr file management app.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

